title: Jose Quan
description:  This is a portfolio containing assignments, projects, and presentations. 

   <br><br>
   <a href="https://www.linkedin.com/in/josecquan/">View My LinkedIn Profile</a> 
  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
